### ISSUE TITLE
Run this project problem

### ISSUE THREAD

**Issue by hahahaaa** [nitesh7sid/fabric-java-sdk-app#1]
I'm a newer for fabric . I want to run this project to study fabric.  
     First step, I start the fabric-simple first-network and change config.json and network-config.json. But I can't found  the "ca": "http://127.0.0.1:...." port in the first-network, can u tell me how to do that ? Thank u very much.  
     Next, I try to run this project in tomcat . But I this problem " java.lang.RuntimeException: TEST is missing cert file /Users/cpf/Downloads/fabric-java-sdk-app/target/fabric-java-sdk-app-0.0.1-SNAPSHOT/fixture/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
" !   Can you  tell me how to generate this crt please.  
     If you can tell me, I'm grateful! thank u!

**Comment by nitesh7sid** [comment]
Hi,
This project demonstrates how can a Java client be used to interact with Hyperledger Fabric. you might need to look at the main hyperledger fabric documentation to learn abt the fabric.
.crt file is generated using the cryptogen tool provided by the Hyperledger fabric. refer to the hyperledger fabric documentation for more details
